eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: '8765'

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: sg-api-gateway
  cloud:
    config:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: sg-user
        uri: lb://sg-user
        predicates:
        - Path=/sg-user/**
      - id: sga-oauth
        uri: lb://sga-oauth
        predicates:
        - Path=/sga-oauth/**
      - id: sg-notificacao
        uri: lb://sg-notificacao
        predicates:
        - Path=/sg-notificacao/**  
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: test
  #main: web-application-type: none 
    
oauth:
  client:
    name: myappname123
    secret: myappsecret123

jwt:
  secret: MY-SECRET   
    

    
#Olhar se precisa    
#zuul.routes.oauth.sensitive-headers=Cookie,Set-Cookie
